### ISSUE TITLE
Disable podofo

### ISSUE THREAD

**Issue by pcoramasionwu** [docwire/docwire#101]
Is there information on how I may  disable podofo in the platform? I don't require it's capability and https://github.com/docwire/docwire/issues/90 is still an issue

**Comment by as-ascii** [comment]
Splitting the SDK into a larger number of smaller libraries is planned to be done soon: #103. The final solution will be not to link the docwire_pdf library.

**Comment by pcoramasionwu** [comment]
Expected Outcome: Podofo is no longer a dependency to run the SDK without issues

**Comment by as-ascii** [comment]
In addition: the documentation should be added what docwire libraries should be explicitly linked to the application for what features and dependencies.

**Comment by as-ascii** [comment]
docwire_office_formats library is splitted into smaller libraries:
- docwire_odf_ooxml
- docwire_ole_office_formats
- docwire_xlsb
- docwire_iwork
- docwire_rtf
- docwire_pdf
- docwire_html
- docwire_plain_text.

podofo is the dependency of docwire_pdf library only.

docwire_office_formats library can be still used to link easily all of that smaller libraries but there is also a possibility to link smaller libraries directly instead. In this scenario docwire_pdf can be just skipped.

This implementation will be merged to main branch together with other recent changes soon.
