### ISSUE TITLE
Docwire build is broken on Windows

### ISSUE THREAD

**Issue by efieleke-tausight** [docwire/docwire#129]
It seems a download referenced by the build is no longer available. This is a critical issue for us, as we have to rebuild docwire because we updated the compiler that we use.

Downloading https://github.com/libyal/libbfio/releases/download/20221025/libbfio-alpha-20221025.tar.gz
error: Failed to download from mirror set
error: https://github.com/libyal/libbfio/releases/download/20221025/libbfio-alpha-20221025.tar.gz: failed: status code 404

**Comment by as-ascii** [comment]
Upstream removed the release after publishing new one... Upgrading in progress, merge estimated in a few hours.
