### ISSUE TITLE
Error during build of docwire on windows

### ISSUE THREAD

**Issue by pcoramasionwu** [docwire/docwire#137]
I receive this error when running 'pwsh -File "build.ps1"' from x64 Native Tools Command Prompt for VS 2022

-- Testing x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: ctest -V --no-tests=error
    Working Directory: C:/Users/workspace/new_docwire/docwire/vcpkg/buildtrees/docwire/x64-windows-dbg
    Error code: 8
    See logs for more information:
      C:\Users\workspace\new_docwire\docwire\vcpkg\buildtrees\docwire\test-docwire-x64-windows-dbg-out.log
      C:\Users\workspace\new_docwire\docwire\vcpkg\buildtrees\docwire\test-docwire-x64-windows-dbg-err.log
Call Stack (most recent call first):
  C:/Users/workspace/new_docwire/docwire/ports/docwire/portfile.cmake:74 (vcpkg_execute_required_process)
  C:/Users/workspace/new_docwire/docwire/ports/docwire/portfile.cmake:99 (run_tests)
  C:/Users/workspace/new_docwire/docwire/ports/docwire/portfile.cmake:145 (run_all_tests)
  scripts/ports.cmake:170 (include)

--------------------------------
C:\Users\workspace\new_docwire\docwire\vcpkg\buildtrees\docwire\test-docwire-x64-windows-dbg-out.log
--------------------------------
UpdateCTestConfiguration  from :C:/Users/workspace/new_docwire/docwire/vcpkg/buildtrees/docwire/x64-windows-dbg/DartConfiguration.tcl
UpdateCTestConfiguration  from :C:/Users/workspace/new_docwire/docwire/vcpkg/buildtrees/docwire/x64-windows-dbg/DartConfiguration.tcl
Test project C:/Users/workspace/new_docwire/docwire/vcpkg/buildtrees/docwire/x64-windows-dbg
Constructing a list of tests

--------------------------------
C:\Users\workspace\new_docwire\docwire\vcpkg\buildtrees\docwire\test-docwire-x64-windows-dbg-err.log
--------------------------------
CMake Error at C:/Program Files/CMake/share/cmake-3.28/Modules/GoogleTestAddTests.cmake:112 (message):
  Error running test executable.
    Path: 'C:/Users//workspace/new_docwire/docwire/vcpkg/buildtrees/docwire/x64-windows-dbg/tests/api_tests.exe'
    Result: Exit code 0xc0000142
    Output:
Call Stack (most recent call first):
  C:/Users/workspace/new_docwire/docwire/vcpkg/buildtrees/docwire/x64-windows-dbg/tests/api_tests[1]_include.cmake:6 (gtest_discover_tests_impl)
  C:/Users/workspace/new_docwire/docwire/vcpkg/buildtrees/docwire/x64-windows-dbg/tests/CTestTestfile.cmake:7 (include)
  CTestTestfile.cmake:8 (subdirs)
Errors while running CTest
Output from these tests are in: C:/Users/workspace/new_docwire/docwire/vcpkg/buildtrees/docwire/x64-windows-dbg/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.

--------------------------------
C:/Users/workspace/new_docwire/docwire/vcpkg/buildtrees/docwire/x64-windows-dbg/Testing/Temporary/LastTest.log
--------------------------------
(Empty)

**Comment by as-ascii** [comment]
The exit code 0xc0000142 is unfortunately very generic one like "The Application was unable to start correctly" so we will need to collect as much data/logs as possible. You can set environment variable DEBUG to value 1 before calling the script to acquire more of them.

In the meantime: you can disable automatic tests editing build.ps1 here:
https://github.com/docwire/docwire/blob/730e98706c152ee23f67ab163aa16552f25e3eef/build.ps1#L82
Just change it to empty string. Leaving square brackets should also work.
Unfortunately there is currently no way to disable it using command line arguments or environment variable.

**Comment by as-ascii** [comment]
Possibility to manage vcpkg flags from build script should be added.

**Comment by pcoramasionwu** [comment]
Expected Outcome: Necessary updates to build & updated documentation (including specification of all necessary dependencies and setup steps) for building successfully & consistently on windows 11.

**Comment by as-ascii** [comment]
In addition:
- VCPKG should be updated to latest version, probably without pinning to specified release so MS can fix the issues on their side without additional steps and delays on DocWire side (it is as well needed for adding the SDK to the official VCPKG repository - that would be perfect but out of scope for now).
- The documentation specific to VCPKG it self should be linked not copied - so it can be updated directly by VCPKG team without additional delays on DocWire side.
- If any vcpkg-specific problems are detected in this issue they should be forwarded to the VCPKG team directly.

**Comment by as-ascii** [comment]
VCPKG was updated to the latest version, pinning to specified vcpkg release was removed so MS can fix the issues on their side without additional steps and delays on DocWire side. Changes will be merged to master branch together with other latest modifications.

**Comment by as-ascii** [comment]
Botan ports are problematic after vcpkg update once again (upgrades in vcpkg repository are fast and require very modern compile environments). In addition Botan is big and we use it currently only for Base64 decoding. So it should be replaced ASAP with other smaller library. We can return to it when it stabilized.

**Comment by as-ascii** [comment]
We will try to integrate https://github.com/aklomp/base64 as it has nice CPU optimizations and is available in vcpkg official repository. It is in C but API is simple and we will provide a wrapper.

**Comment by as-ascii** [comment]
Botan has been replaced with aklomp-base64. docwire_base64 library was introduced as a wrapper.
Possibility to set vcpkg port flags using FEATURES variable was added as well. Automatic tests are disabled by default and can be enabled using "tests" flag. No manual modification of build scripts are required.

Proceeding with installation documentation cleanup and improvements that should be a last step in this issue.

**Comment by as-ascii** [comment]
Installation documentation was redesigned. Links to Microsoft Learn articles were added. Small improvements in installation procedures were introduced in the same time.
