### ISSUE TITLE
Conversion includes hyperlink tags

### ISSUE THREAD

**Issue by efieleke-tausight** [docwire/docwire#142]
If you open a doc in Word, then save it as a text file, it strips out hyperlink tags. Yet docwire keeps those tags when converting from RTF and other formats. Here's an example snippet of what it returns. We would prefer that it leaves the hyperlinks out by default. I have attached an RTF file for your testing purposes.

This may not be considered a bug, but having the option to not include hyperlink tags is important to us.

```
<HYPERLINK "http://www.irs.gov/pub/irs-soi/10esgiftsnaptotal.pdf" h>Amount of total gifts, by tax status of return
<HYPERLINK "http://www.irs.gov/pub/irs-soi/10esgiftsnaptotal.pdf" h>Taxable,
<HYPERLINK "http://www.irs.gov/pub/irs-soi/10esgiftsnaptotal.pdf" h>$8,700,152,512
<HYPERLINK "http://www.irs.gov/pub/irs-soi/10esgiftsnaptotal.pdf" h>Nontaxable,
<HYPERLINK "http://www.irs.gov/pub/irs-soi/10esgiftsnaptotal.pdf" h>$29,171,898,869
<HYPERLINK "http://www.irs.gov/pub/irs-soi/10esgiftsnaptotal.pdf" h>Amount of total gifts, by tax status of return
<HYPERLINK "http://www.irs.gov/pub/irs-soi/10esgiftsnaptotal.pdf" h>Taxable,
<HYPERLINK "http://www.irs.gov/pub/irs-soi/10esgiftsnaptotal.pdf" h>$8,700,152,512
<HYPERLINK "http://www.irs.gov/pub/irs-soi/10esgiftsnaptotal.pdf" h>Nontaxable,
<HYPERLINK "http://www.irs.gov/pub/irs-soi/10esgiftsnaptotal.pdf" h>$29,171,898,869
< SHAPE  * MERGEFORMAT ><HYPERLINK "http://www.irs.gov/taxstats" h>Statiosf tIniccomse
<HYPERLINK "http://www.irs.gov/taxstats" h>Statiosf tIniccomse
```

**Comment by efieleke-tausight** [comment]
[10esgiftsnap.zip](https://github.com/user-attachments/files/16287142/10esgiftsnap.zip)

**Comment by as-ascii** [comment]
- RTF Parser needs to be updated to emit separate docwire::tags::Link structures instead of single docwire::tags::Text tag for whole document
- DOC Parser (old binary MS Word format) - similar
- Constructor arguments needs to be added to PlainTextExporter to set how hyperlinks should be presented (can be std::function for custom styling or simple boolean to enable/disable)

**Comment by pcoramasionwu** [comment]
Expected Outcome: Plain Text document conversion should make display of hyperlinks customizable (with the option to remove them all together). All parsers updated so that hyperlinks are emitted separately

**Comment by as-ascii** [comment]
Uploading Microsoft specification document for latest version of RTF format (v1.9.1):
[Word2007RTFSpec9.pdf](https://github.com/user-attachments/files/16566783/Word2007RTFSpec9.pdf)

**Comment by as-ascii** [comment]
Support for hyperlinks in RTFParser was added. Changes will be merged to master branch together with other recent changes.

**Comment by as-ascii** [comment]
Support for docx hyperlinks in ODFOOXMLParser was added. DOCParser for old binary doc format (OLE) works fine with links.

**Comment by as-ascii** [comment]
Constructor argument was added to PlainTextExporter to set how hyperlinks should be presented, add custom decoration etc.
This is the example usage:
```cpp
auto exporter = std::make_shared<PlainTextExporter>(
        eol_sequence{"\n"},
        link_formatter{
            .format_opening = [](const tag::Link& link){ return (link.url ? "(" + *link.url + ")" : "") + "["; },
            .format_closing = [](const tag::CloseLink& link){ return "]"; }
        });
```
It produces something like:
```
(https://example.com)[Example]
```
To disable urls and leave only text without any marks:
```cpp
auto exporter = std::make_shared<PlainTextExporter>(
        eol_sequence{"\n"},
        link_formatter{
            .format_opening = [](const tag::Link& link){ return ""; },
            .format_closing = [](const tag::CloseLink& link){ return ""; }
        });
```
