### ISSUE TITLE
XML conversions can contain what looks like gobbledy gook

### ISSUE THREAD

**Issue by efieleke-tausight** [docwire/docwire#149]
I have attached an XML file, as well as the conversion results. Note that the conversion results contain a large block of nonsense text.

**Comment by efieleke-tausight** [comment]
[07ubgraph2.zip](https://github.com/user-attachments/files/17099213/07ubgraph2.zip)

**Comment by as-ascii** [comment]
As a quick solution "w:binData" tag have to be filtered out in XMLParser as it contains that kind of data as a text inside (not as an attribute). That can be just added in the nearest release.

After file type detection will be improved the dedicated MSWord XML parser will not give us such suprises.
