### ISSUE TITLE
The command line fails in windows x64 and vs2019. Procedure

### ISSUE THREAD

**Issue by Haye1213** [docwire/docwire#159]
As mentioned in the title, when I entered the command line after preparing the environment, I was prompted to fail when I entered the next item. The following is my error message and log file attachment. How should I solve this situation? Looking forward to your reply, Thank you very much!
```
Installing 1/1 docwire:x64-windows@latest...
Building docwire:x64-windows@latest...
C:\Users\Test\Desktop\docwire-2024.10.15\ports\docwire: info: installing overlay port from here
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/Test/Desktop/docwire-2024.10.15/vcpkg/buildtrees/docwire/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Test\Desktop\docwire-2024.10.15\vcpkg\buildtrees\docwire\config-x64-windows-dbg-CMakeCache.txt.log
      C:\Users\Test\Desktop\docwire-2024.10.15\vcpkg\buildtrees\docwire\config-x64-windows-rel-CMakeCache.txt.log
      C:\Users\Test\Desktop\docwire-2024.10.15\vcpkg\buildtrees\docwire\config-x64-windows-dbg-CMakeConfigureLog.yaml.log
      C:\Users\Test\Desktop\docwire-2024.10.15\vcpkg\buildtrees\docwire\config-x64-windows-rel-CMakeConfigureLog.yaml.log
      C:\Users\Test\Desktop\docwire-2024.10.15\vcpkg\buildtrees\docwire\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:269 (vcpkg_execute_required_process)
  C:/Users/Test/Desktop/docwire-2024.10.15/ports/docwire/portfile.cmake:17 (vcpkg_cmake_configure)
  scripts/ports.cmake:192 (include)


error: building docwire:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle docwire:x64-windows: 7.1 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+docwire
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[docwire]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2FTest%2FDesktop%2Fdocwire-2024.10.15%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
```
At the same time, I also want to ask if I can get a self-compiled docwire.exe to use after this operation is completed? If not, how do I compile a docwire.exe or docwire.dll
[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/user-attachments/files/17541145/config-x64-windows-dbg-CMakeCache.txt.log)
[config-x64-windows-dbg-CMakeConfigureLog.yaml.log](https://github.com/user-attachments/files/17541146/config-x64-windows-dbg-CMakeConfigureLog.yaml.log)
[config-x64-windows-out.log](https://github.com/user-attachments/files/17541147/config-x64-windows-out.log)
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/user-attachments/files/17541148/config-x64-windows-rel-CMakeCache.txt.log)
[config-x64-windows-rel-CMakeConfigureLog.yaml.log](https://github.com/user-attachments/files/17541150/config-x64-windows-rel-CMakeConfigureLog.yaml.log)

**Comment by as-ascii** [comment]
There is an information in the log files that doxygen utility is missing:

```
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
```

Unfortunately there is no way currently to add doxygen as a dependency in vcpkg and it needs to be manually installed.
There are several ways for sure to do it, we are using chocolatey on CI machines like specified in build.yml:

```${{ runner.os == 'Windows' && 'choco install doxygen.install graphviz -y' || '' }}```

After successful installation via vcpkg the CLI utility will be available in "tools" directory inside vcpkg tree.

**Comment by as-ascii** [comment]
https://www.doxygen.nl/manual/install.html

**Comment by Haye1213** [comment]
According to your reply, I have successfully executed the command line and now everything is normal, thank you very much!
