### ISSUE TITLE
Readme short does not say a word about PDF files 

### ISSUE THREAD

**Issue by Novitzmann** [docwire/docwire#46]
As mentioned, short readme at the top doesnt include PDF in description. Marketing error

**Comment by as-ascii** [comment]
That is true, DocWire SDK supports extracting text and other data from "Portable Document Format" (PDF) and it was missing in project description. The "about" section of the project has been updated. This is more general description now and does not include list supported formats (it's too long, DocWire SDK supports nearly 100 filename extensions in data extracting / text extracting procedure). Supported formats are described in "Features" section in more detail.
