### ISSUE TITLE
Application is crashing when using the doctotext Library.

### ISSUE THREAD

**Issue by skothala09** [docwire/docwire#93]
I have build the sample application using the 5.0.9 library. When I am trying to run I am getting the below error.

terminate called after throwing an instance of 'doctotext::Exception'
  what():  std::exception
Aborted
Attaching the sample code and folder. Please help in resolving this.
[build.zip](https://github.com/docwire/docwire/files/14295148/build.zip)
[Doc2text.zip](https://github.com/docwire/docwire/files/14295164/Doc2text.zip)

I am exporting the build folder path and then running the binary.
And do we need to place the executable and the library files in same folder?

**Comment by as-ascii** [comment]
The "example" binary located in "build" directory works well. Please find the screenshot below. It is sufficient to 
![image](https://github.com/docwire/docwire/assets/62467072/53baeac6-181f-4857-908f-949190f55b2c)
Please check if you added command line argument in the invocation and is file path correct. These simple examples usually do not check "corner cases" and similar exception is generated when incorrect input file path is provided.
We also checked on clean ubuntu 20.04 using:
```bash
docker run --rm -v "$PWD/build:/docwire" ubuntu:20.04 /bin/bash -c 'apt update && apt install libxml2 libpng16-16 fontconfig libwebpmux3 libopenjp2-7 libgomp1 -y && cd /docwire && LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./example DocToText_Benchmarks.pdf'
```
and it works correctly.

However please remember that old v5.0.9 is not maintained and supported currently.
